### ISSUE TITLE
Missing pagination `parentField` when set `@Pagination` annotation on existent field (EXTRA_LAZY)

### ISSUE THREAD

**Issue by rafrsr** [ynloultratech/graphql-bundle#12]
When use `@Pagination` annotation to define some options on existent field `EXTRA_LAZY` with automatic pagination the parent field should be declared manually.

example:
````
/**
 * @var Collection|ProductCategory[]
 *
 * @GraphQL\Expose()
 *
 * @GraphQL\Field(options={
 *     @GraphQL\Plugin\Pagination(orderBy={"*", "parentName": "parent.name"}, parentField="parent", parentRelation="ONE_TO_MANY")
 * })
 * @ORM\OneToMany(targetEntity="App\Entity\ProductCategory", mappedBy="parent", fetch="EXTRA_LAZY")
 */
private $children;
````
This only happens when use the `@Pagination` annotation to add some extra config, otherwise works as expected.

**Comment by yceruto** [comment]
However, I tried without `parentRelation="ONE_TO_MANY"` and it works, not sure if it's important.

**Comment by rafrsr** [comment]
`ONE_TO_MANY` is the default if no one is specified 😉
